version: "3.8"

services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    container_name: $MONGODB_NAME
    restart: always
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_NAME
  
  redis:
    image: redis:latest
    env_file:
      - .env
    container_name: $REDIS_NAME
    restart: always
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    environment:
      REDIS_USER: $REDIS_USER
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
