version: '3.8'

services:
  ufabc-next-db:
    image: mongo:latest
    container_name: ufabc-next-db
    ports:
      - 27017:27017
  ufabc-next-redis:
    image: redis:latest
    container_name: ufabc-next-redis
    ports:
      - 6379:6379
    environment:
      REDIS_USER: default
      REDIS_PORT: 6379
      REDIS_PASSWORD: qj6wGxXINcQyWXdN
