services:
  next-db:
    image: mongo:latest
    container_name: next-db
    ports:
      - 27017:27017
    volumes:
      - ./scripts/docker/mongo/initdb.d:/docker-entrypoint-initdb.d:ro
      - next-db-data:/data/db/

  next-redis:
    image: redis:latest
    container_name: next-redis
    ports:
      - 6379:6379
    environment:
      REDIS_USER: default
      REDIS_PORT: 6379
      REDIS_PASSWORD: qj6wGxXINcQyWXdN

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack gateway
      - "4571:4571" # Alternative API gateway
    environment:
      SERVICES: "s3,lambda,dynamodb,sqs,sns,ses"
      AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID_LOCALSTACK"
      AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY_LOCALSTACK"
      DEBUG: "1"
    volumes:
      - "./scripts/docker/localstack:/var/lib/localstack"
      - "./scripts/init-localstack.sh:/etc/localstack/init/ready.d/init.sh"

volumes:
  next-db-data:
    driver: local
    name: next-mongo
