packages:
  - apps/*
  - packages/*
catalog:
  "@aws-sdk/client-s3": ^3.984.0
  "@aws-sdk/client-ses": ^3.984.0
  "@aws-sdk/types": ^3.973.1
  "@aws-sdk/lib-storage": ^3.984.0
  "@aws-sdk/s3-request-presigner": ^3.984.0
  "@axiomhq/pino": ^1.4.0
  "@bull-board/api": ^6.16.4
  "@bull-board/fastify": ^6.16.4
  "@fastify/autoload": ^6.3.1
  "@fastify/cookie": ^11.0.2
  "@fastify/cors": ^10.1.0
  "@fastify/env": ^5.0.3
  "@fastify/jwt": ^9.1.0
  "@fastify/multipart": ^9.4.0
  "@fastify/oauth2": ^8.1.2
  "@fastify/rate-limit": ^10.3.0
  "@fastify/redis": ^7.2.0
  "@fastify/request-context": ^6.2.1
  "@fastify/sensible": ^6.0.4
  "@fastify/swagger": ^9.6.1
  "@fastify/swagger-ui": ^5.2.5
  "@notionhq/client": ^2.3.0
  "@scalar/fastify-api-reference": ^1.35.5
  "@testcontainers/localstack": ^11.11.0
  "@testcontainers/mongodb": ^11.11.0
  "@testcontainers/redis": ^11.11.0
  "@total-typescript/ts-reset": ^0.5.1
  "@types/aws-lambda": 8.10.155
  "@types/lodash-es": ^4.17.12
  "@types/ms": ^0.7.34
  "@types/node": ^22.19.9
  "@types/string-similarity": ^4.0.2
  "@wppconnect-team/wppconnect": ^1.37.8
  bullmq: ^5.67.3
  c8: ^10.1.3
  cheerio: ^1.2.0
  close-with-grace: ^1.3.0
  fastify: ^5.7.4
  fastify-plugin: ^4.5.1
  fastify-tsconfig: ^2.0.0
  fastify-type-provider-zod: ^3.0.0
  fastify-zod-openapi: ^3.0.4
  ioredis: ^5.7.0
  lodash-es: ^4.17.23
  lru-weak-cache: ^0.3.3
  mongoose: ^9.1.6
  ms: ^2.1.3
  nock: ^14.0.10
  ofetch: ^1.5.1
  oxfmt: ^0.22.0
  oxlint: ^1.43.0
  oxlint-tsgolint: ^0.10.1
  pino: 10.1.0
  pino-pretty: ^13.1.3
  rimraf: ^6.1.2
  string-similarity: ^4.0.4
  testcontainers: ^10.28.0
  ts-patch: ^3.3.0
  tsup: ^8.5.1
  tsx: ^4.21.0
  turbo: ^2.8.3
  typescript: ^5.9.3
  typescript-transform-paths: ^3.5.6
  ulidx: ^2.4.1
  ultracite: ^7.1.4
  vite-tsconfig-paths: ^6.0.5
  vitest: ^4.0.18
  zod: ^3.25.76
  zod-openapi: ^3.3.0
  zod-to-json-schema: ^3.25.1
