packages:
  - apps/*
  - packages/*
catalog:
  "@aws-sdk/client-s3": ^3.956.0
  "@aws-sdk/client-ses": ^3.956.0
  "@axiomhq/pino": ^1.3.1
  "@biomejs/biome": ^1.9.4
  "@bull-board/api": ^6.15.0
  "@bull-board/fastify": ^6.15.0
  "@fastify/autoload": ^6.3.1
  "@fastify/cookie": ^11.0.2
  "@fastify/cors": ^10.1.0
  "@fastify/env": ^5.0.3
  "@fastify/jwt": ^9.1.0
  "@fastify/multipart": ^9.3.0
  "@fastify/oauth2": ^8.1.2
  "@fastify/rate-limit": ^10.3.0
  "@fastify/request-context": ^6.2.1
  "@fastify/sensible": ^6.0.4
  "@fastify/swagger": ^9.6.1
  "@fastify/swagger-ui": ^5.2.3
  "@notionhq/client": ^2.3.0
  "@total-typescript/ts-reset": ^0.5.1
  "@types/lodash-es": ^4.17.12
  "@types/ms": ^0.7.34
  "@types/node": ^22.19.3
  "@types/string-similarity": ^4.0.2
  "@aws-sdk/types": ^3.957.0
  bullmq: ^5.66.2
  c8: ^10.1.3
  cheerio: ^1.1.2
  close-with-grace: ^1.3.0
  fastify: ^5.6.2
  fastify-plugin: ^4.5.1
  fastify-tsconfig: ^2.0.0
  fastify-zod-openapi: ^3.0.4
  lodash-es: ^4.17.22
  lru-weak-cache: ^0.3.3
  mongoose: ^8.20.4
  ms: ^2.1.3
  ofetch: ^1.5.1
  pino: 10.1.0
  pino-pretty: ^13.1.3
  rimraf: ^6.1.2
  string-similarity: ^4.0.4
  testcontainers: ^10.28.0
  ts-patch: ^3.3.0
  tsup: ^8.5.1
  tsx: ^4.21.0
  turbo: ^2.7.1
  typescript: ^5.9.3
  typescript-transform-paths: ^3.5.5
  ulidx: ^2.4.1
  zod: ^3.25.76
  zod-openapi: ^3.3.0
  zod-to-json-schema: ^3.25.0
  fastify-type-provider-zod: ^3.0.0
