/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "WhatsAppQrcodes": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "WhatsAppTokens": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "next-whats-api": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "vpc-main-iac": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}